"""Point Structure."""
from rules.drawable import *
polygonADT = {
    is_a:None,
    "new":{
        (Point,):{
            args:("pointList"),
            trgt:Polygon.fromPoints,
        },
        (Line,):{
            args:("lineList",),
            trgt:Polygon.fromLines,
        },
        ret:Polygon
    },
    "copy":{
        tuple():{
            args:tuple(),
            trgt:Polygon.fromPolygon
        },
        ret:Circle
    },
    "area":{
        tuple():{
            args:tuple(),
            trgt:Polygon.area
        },
        ret:float
    },
    "signedArea":{
        tuple():{
            args:tuple,
            trgt:Polygon.signedArea
        }
    },
    "centroid":{
        tuple():{
            args:tuple(),
            trgt:Polygon.centroid
        },
        ret:Point
    },
    "vertexCentroid":{
        tuple():{
            args:tuple(),
            trgt:Polygon.vertexCentroid
        },
        ret:Point
    },
    "internalAngle":{
        (int,):{
            args:("idx",),
            trgt:Polygon.internAngle
        },
        (Point,):{
            args:("point",),
            trgt:Polygon.internAngle
        },
        ret:float
    },
    "angleBisector":{
        (int,):{
            args:("idx",),
            trgt:Polygon.angleBisector
        },
        (Point,):{
            args:("point",),
            trgt:Polygon.angleBisector
        },
        ret:Line
    }
}