"""Point Structure."""
from rules.drawable import *
polygonADT = {
    is_a:None,
    "new":{
        (list, Point,):{
            args:("listOfPoints",),
            trgt:Polygon.fromPoints,
        },
        (list, Line,):{
            args:("listOfLine",),
            trgt:Polygon.fromLines,
        },
        retVal:Polygon
    },
    "copy":{
        tuple():{
            args:tuple(),
            trgt:Polygon.fromPolygon
        },
        retVal:Polygon
    },
    "area":{
        tuple():{
            args:tuple(),
            trgt:Polygon.area
        },
        retVal:float
    },
    "getPointFromID":{
        (float,):{
            args:("idx",),
            trgt:Polygon.getIndexedPoint
        },
        retVal:Point
    },
    "getLineFromID":{
        (float,):{
            args:("idx",),
            trgt:Polygon.getIndexedLine
        },
        retVal:Line
    },
    "signedArea":{
        tuple():{
            args:tuple(),
            trgt:Polygon.signedArea
        },
        retVal:float
    },
    "centroid":{
        tuple():{
            args:tuple(),
            trgt:Polygon.centroid
        },
        retVal:Point
    },
    "vertexCentroid":{
        tuple():{
            args:tuple(),
            trgt:Polygon.vertexCentroid
        },
        retVal:Point
    },
    "internalAngle":{
        (float,):{
            args:("idx",),
            trgt:Polygon.internAngle
        },
        (Point,):{
            args:("point",),
            trgt:Polygon.internAngle
        },
        retVal:float
    },
    "angleBisector":{
        (float,):{
            args:("idx",),
            trgt:Polygon.angleBisector
        },
        (Point,):{
            args:("point",),
            trgt:Polygon.angleBisector
        },
        retVal:Line
    }
}